server:
  port: 8989
spring:
  #配置数据源
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_blog?characterEncoding=utf-8&serverTimezone=UTC
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    #文件上传
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    password: 123456
    host: 192.168.222.10
    port: 6379

mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局配置-逻辑删除字段自动补全
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto